engines:
  duplication:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
#  shellcheck:
#    enabled: true
#  markdownlint:
#    enabled: true
#ratings:
#  paths:
#  - app/**
#  - lib/**
#  - "**.rb"
#  - "**.go"
exclude_paths:
- bin/*
- build/*
- *.md
- *.yml
