engines:
  duplication: #seems to be working
    enabled: true
    config:
      languages:
      - javascript
  fixme: #seems to be working
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
      - TODO
      - todo
  eslint: #no idea if needs config https://docs.codeclimate.com/docs/eslint
    enabled: true
    config:
      extensions:
      - .es6
      - .js
      - .user.js
      - .jsx
  csslint: #seems to be working
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.user.js"
  - "**.js"
  - "**.css"
  - "**.sh"
  - "**.bat"
  - "**.md"
exclude_paths:
- bin/*
- build/*
#- "**.md"
- "**.yml"
