engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
      - TODO
      - todo
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
      - .user.js
      - .jsx
  csslint:
    enabled: true
#  shellcheck:
#    enabled: true
#  markdownlint:
#    enabled: true
ratings:
  paths:
  - "**.user.js"
  - "**.js"
  - "**.css"
  - "**.sh"
  - "**.bat"
exclude_paths:
- bin/*
- build/*
- "**.md"
- "**.yml"
