engines:
  duplication:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
#  shellcheck:
#    enabled: true
#  markdownlint:
#    enabled: true
ratings:
  paths:
  - "**.user.js"
  - "**.js"
  - "**.css"
  - "**.sh"
  - "**.bat"
exclude_paths:
- bin/*
- build/*
- "**.md"
#- "**.yml"
