language: node_js
node_js:
  - "4.2.0"

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  
before_script:
  - npm install -g grunt-cli
  - cd build
  - java -jar build.jar
