# Test against this version of Node.js
environment:
  nodejs_version: "0.12.7"
  access_token:
   secure: G8waKkParfgirZh3PKxylzY7tRDL4expH+CRtNjsh3FpKrfnzPld2nYsn+FQtn07

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g esformatter

# Appveyor doesn"t have JDK 8 by default in PATH so we must set it

build_script: 
# is there a better way to do this?
 - cmd: SET tempath=%PATH%
 - cmd: SET PATH="C:\Program Files\Java\jdk1.8.0\bin"
 - build.bat

skip_commits:
  # Regex for matching commit message
  message: /Automated Appveyor build/
  # Commit author's username, name, email or regexp maching one of these.
  author: Appveyor Automated Build

# Note: AppVeyor checkout only the last commit and not the entire branch. So you may have to checkout the wanted branch: git checkout master
on_success:
 - cmd: SET PATH=%tempath%
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "bbbbbbenes@outlook.com.br"
 - git config --global user.name "Appveyor Automated Build"
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a:%%b)
# Bug: when someone commits multiple times too fast, the build will fail - enabling rolling builds may fix this
 - git checkout master
 - git add bin/*
 - git commit -m "Automated Appveyor build at %mydate%, %mytime% [skip ci]"
# beautify
 - esformatter -i **.user.js
 - git add **.user.js
 - git commit -m "Automated code formatting at %mydate%, %mytime% [skip ci]"
 - git push origin master
